package com.ddx.manage.system.model;

import java.io.Serializable;
import java.util.Date;

public class User implements Serializable{
    private static final long serialVersionUID = 7882653218461150968L;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_USER.ID
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_USER.SU_LOGIN_NAME
     *
     * @mbg.generated
     */
    private String loginName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_USER.SU_PASSWORD
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_USER.SU_REAL_NAME
     *
     * @mbg.generated
     */
    private String realName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_USER.SU_MOBILE
     *
     * @mbg.generated
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_USER.SU_ENCRYPT_SALT
     *
     * @mbg.generated
     */
    private String encryptSalt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_USER.SU_TYPE
     *
     * @mbg.generated
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_USER.SU_STATUS
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_USER.SU_OPERATOR
     *
     * @mbg.generated
     */
    private String operator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_USER.SU_OPERATE_TIME
     *
     * @mbg.generated
     */
    private Date operateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_USER.ID
     *
     * @return the value of SYSTEM_USER.ID
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_USER.ID
     *
     * @param id the value for SYSTEM_USER.ID
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_USER.SU_LOGIN_NAME
     *
     * @return the value of SYSTEM_USER.SU_LOGIN_NAME
     *
     * @mbg.generated
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_USER.SU_LOGIN_NAME
     *
     * @param loginName the value for SYSTEM_USER.SU_LOGIN_NAME
     *
     * @mbg.generated
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName == null ? null : loginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_USER.SU_PASSWORD
     *
     * @return the value of SYSTEM_USER.SU_PASSWORD
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_USER.SU_PASSWORD
     *
     * @param password the value for SYSTEM_USER.SU_PASSWORD
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_USER.SU_REAL_NAME
     *
     * @return the value of SYSTEM_USER.SU_REAL_NAME
     *
     * @mbg.generated
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_USER.SU_REAL_NAME
     *
     * @param realName the value for SYSTEM_USER.SU_REAL_NAME
     *
     * @mbg.generated
     */
    public void setRealName(String realName) {
        this.realName = realName == null ? null : realName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_USER.SU_MOBILE
     *
     * @return the value of SYSTEM_USER.SU_MOBILE
     *
     * @mbg.generated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_USER.SU_MOBILE
     *
     * @param mobile the value for SYSTEM_USER.SU_MOBILE
     *
     * @mbg.generated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_USER.SU_ENCRYPT_SALT
     *
     * @return the value of SYSTEM_USER.SU_ENCRYPT_SALT
     *
     * @mbg.generated
     */
    public String getEncryptSalt() {
        return encryptSalt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_USER.SU_ENCRYPT_SALT
     *
     * @param encryptSalt the value for SYSTEM_USER.SU_ENCRYPT_SALT
     *
     * @mbg.generated
     */
    public void setEncryptSalt(String encryptSalt) {
        this.encryptSalt = encryptSalt == null ? null : encryptSalt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_USER.SU_TYPE
     *
     * @return the value of SYSTEM_USER.SU_TYPE
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_USER.SU_TYPE
     *
     * @param type the value for SYSTEM_USER.SU_TYPE
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_USER.SU_STATUS
     *
     * @return the value of SYSTEM_USER.SU_STATUS
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_USER.SU_STATUS
     *
     * @param status the value for SYSTEM_USER.SU_STATUS
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_USER.SU_OPERATOR
     *
     * @return the value of SYSTEM_USER.SU_OPERATOR
     *
     * @mbg.generated
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_USER.SU_OPERATOR
     *
     * @param operator the value for SYSTEM_USER.SU_OPERATOR
     *
     * @mbg.generated
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_USER.SU_OPERATE_TIME
     *
     * @return the value of SYSTEM_USER.SU_OPERATE_TIME
     *
     * @mbg.generated
     */
    public Date getOperateTime() {
        return operateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_USER.SU_OPERATE_TIME
     *
     * @param operateTime the value for SYSTEM_USER.SU_OPERATE_TIME
     *
     * @mbg.generated
     */
    public void setOperateTime(Date operateTime) {
        this.operateTime = operateTime;
    }
}